In [1]:
import pandas as pd
import numpy as np
from keras.utils import np_utils

Using TensorFlow backend.
C:\Users\DAVE\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\DAVE\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\DAVE\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\DAVE\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:519

In [2]:
df = pd.read_csv("D:/CS/iris.csv")
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [3]:
features = list(df.columns[:4])

x = df[features]

import numpy
x = numpy.array(x)

y = list(df['species'])

import numpy
y = numpy.array(y)

In [4]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
y1 = encoder.fit_transform(y)
y = pd.get_dummies(y1).values
y

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0,

In [5]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.30, random_state=0)

In [6]:
import keras
from keras.models import Sequential
from keras.optimizers import SGD, Adam
from keras.layers import Dense, Dropout, Activation

In [7]:
model = Sequential()
model.add(Dense(output_dim = 3, init = 'uniform', activation = 'relu', input_dim = 4))
model.add(Dense(output_dim = 5, init = 'uniform', activation = 'relu'))
model.add(Dense(output_dim = 3, init = 'uniform', activation = 'softmax'))

model.compile(optimizer = 'adam', loss='categorical_crossentropy', metrics=['accuracy'])

C:\Users\DAVE\anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=4, units=3, kernel_initializer="uniform")`
  
C:\Users\DAVE\anaconda3\lib\site-packages\ipykernel_launcher.py:3: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=5, kernel_initializer="uniform")`
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\DAVE\anaconda3\lib\site-packages\ipykernel_launcher.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="softmax", units=3, kernel_initializer="uniform")`
  after removing the cwd from sys.path.


In [8]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 3)                 15        
_________________________________________________________________
dense_2 (Dense)              (None, 5)                 20        
_________________________________________________________________
dense_3 (Dense)              (None, 3)                 18        
Total params: 53
Trainable params: 53
Non-trainable params: 0
_________________________________________________________________


In [9]:
model.fit(x_train, y_train, epochs=200, batch_size=5, shuffle=True)


Epoch 1/200
105/105 [==============================] - 0s 2ms/step - loss: 1.0987 - accuracy: 0.2762
Epoch 2/200
105/105 [==============================] - 0s 415us/step - loss: 1.0984 - accuracy: 0.3810
Epoch 3/200
105/105 [==============================] - 0s 346us/step - loss: 1.0975 - accuracy: 0.3714
Epoch 4/200
105/105 [==============================] - 0s 315us/step - loss: 1.0961 - accuracy: 0.3714
Epoch 5/200
105/105 [==============================] - 0s 591us/step - loss: 1.0940 - accuracy: 0.3714
Epoch 6/200
105/105 [==============================] - 0s 429us/step - loss: 1.0909 - accuracy: 0.3714
Epoch 7/200
105/105 [==============================] - 0s 615us/step - loss: 1.0855 - accuracy: 0.3714
Epoch 8/200
105/105 [==============================] - 0s 379us/step - loss: 1.0794 - accuracy: 0.3714
Epoch 9/200
105/105 [==============================] - 0s 372us/step - loss: 1.0719 - accuracy: 0.3714
Epoch 10/200
105/105 [==============================] - 0s 701us/step - lo

105/105 [==============================] - 0s 477us/step - loss: 0.5495 - accuracy: 0.7048
Epoch 78/200
105/105 [==============================] - 0s 410us/step - loss: 0.5464 - accuracy: 0.7048
Epoch 79/200
105/105 [==============================] - 0s 486us/step - loss: 0.5434 - accuracy: 0.7048
Epoch 80/200
105/105 [==============================] - 0s 419us/step - loss: 0.5409 - accuracy: 0.7048
Epoch 81/200
105/105 [==============================] - 0s 448us/step - loss: 0.5378 - accuracy: 0.7048
Epoch 82/200
105/105 [==============================] - 0s 477us/step - loss: 0.5358 - accuracy: 0.7048
Epoch 83/200
105/105 [==============================] - 0s 419us/step - loss: 0.5327 - accuracy: 0.7048
Epoch 84/200
105/105 [==============================] - 0s 521us/step - loss: 0.5296 - accuracy: 0.7143
Epoch 85/200
105/105 [==============================] - 0s 458us/step - loss: 0.5276 - accuracy: 0.7143
Epoch 86/200
105/105 [==============================] - 0s 334us/step - loss:

Epoch 155/200
105/105 [==============================] - 0s 400us/step - loss: 0.3809 - accuracy: 0.8762
Epoch 156/200
105/105 [==============================] - 0s 362us/step - loss: 0.3786 - accuracy: 0.8762
Epoch 157/200
105/105 [==============================] - 0s 338us/step - loss: 0.3765 - accuracy: 0.8762
Epoch 158/200
105/105 [==============================] - 0s 343us/step - loss: 0.3757 - accuracy: 0.8667
Epoch 159/200
105/105 [==============================] - 0s 429us/step - loss: 0.3752 - accuracy: 0.8952
Epoch 160/200
105/105 [==============================] - 0s 429us/step - loss: 0.3711 - accuracy: 0.8952
Epoch 161/200
105/105 [==============================] - 0s 376us/step - loss: 0.3693 - accuracy: 0.8952
Epoch 162/200
105/105 [==============================] - 0s 353us/step - loss: 0.3682 - accuracy: 0.8762
Epoch 163/200
105/105 [==============================] - 0s 343us/step - loss: 0.3659 - accuracy: 0.9048
Epoch 164/200
105/105 [==============================] 

In [10]:
scores = model.evaluate(x_test, y_test)
print("\nAccuracy: %.2f%%" % (scores[1]*100))

45/45 [==============================] - 0s 1ms/step

Accuracy: 82.22%


In [11]:
y_pred = model.predict(x_test)

In [12]:
x_test[1,:],y_pred[1]

(array([6. , 2.2, 4. , 1. ]),
 array([0.0213198, 0.6348992, 0.343781 ], dtype=float32))

In [13]:
y_pred_class = np.argmax(y_pred[1])
print(y_pred_class)

1


In [14]:
model.save('model_file.iris')

In [15]:
import numpy as np 
from keras.models import load_model

In [16]:
iris_model = load_model('model_file.iris')



In [17]:
T = np.array([4.9,3.0,1.4,0.2])
data = np.reshape(T, (4,))
print(data.shape)




(4,)


In [20]:
predictions = iris_model.predict([data])



ValueError: Error when checking input: expected dense_1_input to have shape (4,) but got array with shape (1,)

In [21]:
predictions = iris_model.predict([6,2,1.8,2])

ValueError: Error when checking input: expected dense_1_input to have shape (4,) but got array with shape (1,)